### ISSUE TITLE
Customed data generator

### ISSUE THREAD

**Issue by ZhengPeng7** [Neerajj9/CSRNet-keras#13]
Hi, thanks for sharing your code at first.
In the README, you mentioned that you have a [**custom data generator**](https://github.com/Neerajj9/CSRNet-keras#vairable-size-input):
> Thus, we built a custom data generator in keras to efficiently train variable sized images. With a data generator, efficient memory usage takes place and the time taken for training reduces drastically.

I've gone through the codes for times, but still can't find the related code that can make model train on inputs with different shapes.

**Comment by Neerajj9** [comment]
The image_generator() function is the custom data generator

**Comment by ZhengPeng7** [comment]
But the image_generator cannot put **variable** sized images into one batch as it's described.

**Comment by Neerajj9** [comment]
The readme only describes ways to handle the variable size images. It is also specifies that 'The ShanghaiTech dataset does not contain many images having the same image size and thus such batches could not be made' so finally we use a data generator that takes one image at a time instead of loading all images in the memory at once

**Comment by ThanhNhann** [comment]
@Neerajj9 If with TRANCOS dataset, the size of images is the same, should I increase batch to decrease time to training?
